### ISSUE TITLE
creating an app action for a hidden app shows "The app with package name %s isn't installed" when performing

### ISSUE THREAD

**Issue by sds100** [sds100/KeyMapper#503]
- this seems to happen with all hidden apps. The user chose the "Prime Video" app and the "TV" app.

- this doesn't happen with normal apps

**Comment by noviluni** [comment]
It would be amazing to have this working :)

**Comment by sds100** [comment]
fixed

**Comment by brianmichaelwendt** [comment]
I am still getting this issue ("package not installed for hidden apps") on KeyMapper 2.2.0 on my Samsung Galaxy Tab S7+ SM-T970 running Android 11

**Comment by sds100** [comment]
Hello, if you install 2.3.0 (from github for example) do you still have the issue?

**Comment by brianmichaelwendt** [comment]
How do I install from github, is there an APK I can download? I downloaded the code and extracted the ZIP, but I don't know what to do from there. Do I need a compiler to build it?

Thanks,

Brian Wendt
***@***.***
________________________________

**Comment by sds100** [comment]
https://github.com/sds100/KeyMapper/releases You can get all the releases here 🙂

**Comment by brianmichaelwendt** [comment]
Thanks, I found the APK but when I try to install it, it says "Installing..." but after about 5-10 seconds it says "App not installed"

Brian
________________________________

**Comment by sds100** [comment]
You can't install the github version over the google play version so just install the **debug** version. you will then have 2 key mappers. you can remove the debug version once we're done fixing this issue. :)

**Comment by brianmichaelwendt** [comment]
I installed the debug version, then disabled all mappings in the release version.

  In the debug version I created three mappings, all for an external (bluetooth) numeric keypad:

  1) Mapped the "7" key to Instagram, this worked.

  2) Mapped the "DEL" key to a hidden application named "Apps". I had hoped this would open the Apps Drawer. It did not work. There were no messages and it was silently ignored. From the log file attached below, I noticed packageName=com.samsung.android.app.appsedge . The edge panel is a samsung-specific feature, so perhaps this package is not the Apps Drawer, but a hidden service.

  3) Mapped the "." key to a hidden application named "Downloads". I had hoped this would open the Downloads folder. As with #2, no messages and silently ignored. Unlike #2, from the log it appears that KeyMapper did not try to run it, as it says consumed: false

  Here is the log file:

11:50:50.406  Battery optimisation is enabled
11:50:50.430  Battery optimisation is enabled
11:50:56.416  Battery optimisation is enabled
11:50:58.677  Battery optimisation is enabled
11:51:02.260  Battery optimisation is enabled
11:51:07.308  Battery optimisation is enabled
11:51:11.786  Battery optimisation is enabled
11:51:11.851  MainActivity: onResume. Version: 2.3.0-debug
11:51:24.486  Enable service by opening accessibility settings
11:51:37.001  Accessibility service: onCreate
11:51:37.051  Accessibility service: onServiceConnected
11:51:37.522  Accessibility service: checking if it is crashed
11:52:20.687  MainActivity: onResume. Version: 2.3.0-debug
11:52:20.775  Accessibility service: checking if it is crashed
11:52:20.781  Battery optimisation is enabled
11:53:05.486  MainActivity: onResume. Version: 2.3.0-debug
11:53:05.534  Accessibility service: checking if it is crashed
11:53:05.535  Battery optimisation is disabled
11:53:16.234  Accessibility service: checking if it is crashed
11:53:21.340  Accessibility service: checking if it is crashed
11:53:21.556  MainActivity: onResume. Version: 2.3.0-debug
11:53:26.831  Accessibility service: checking if it is crashed
11:53:32.972  Accessibility service: checking if it is crashed
11:54:03.443  Accessibility service: checking if it is crashed
11:54:04.477  Accessibility service: checking if it is crashed
11:54:19.020  Accessibility service: checking if it is crashed
11:54:22.826  Accessibility service: checking if it is crashed
11:54:49.366  Accessibility service: checking if it is crashed
11:54:52.089  Accessibility service: checking if it is crashed
11:55:06.097  MainActivity: onResume. Version: 2.3.0-debug
11:55:06.228  Accessibility service: checking if it is crashed
11:55:06.229  Battery optimisation is disabled
11:55:35.689  MainActivity: onResume. Version: 2.3.0-debug
11:55:35.748  Accessibility service: checking if it is crashed
11:55:35.749  Battery optimisation is disabled
11:56:41.114  Down KEYCODE_NUMPAD_7, key code: 151, time since event: 3ms, device name: Wireless Numeric KeyPad Keyboard, descriptor: ac1ac0a0834a73ca12bdb5aa92681193d22281b7, device id: 26, is external: true, meta state: 2097152, scan code: 71
11:56:41.129  Performed action OpenAppAction(packageName=com.instagram.android), input event type: DOWN_UP, key meta state: 2097152
11:56:41.130  Down KEYCODE_NUMPAD_7 - consumed: true, key code: 151, time since event: 3ms, device name: Wireless Numeric KeyPad Keyboard, descriptor: ac1ac0a0834a73ca12bdb5aa92681193d22281b7, device id: 26, is external: true, meta state: 2097152, scan code: 71
11:56:41.239  Up KEYCODE_NUMPAD_7, key code: 151, time since event: 6ms, device name: Wireless Numeric KeyPad Keyboard, descriptor: ac1ac0a0834a73ca12bdb5aa92681193d22281b7, device id: 26, is external: true, meta state: 2097152, scan code: 71
11:56:41.240  Up KEYCODE_NUMPAD_7 - consumed: true, key code: 151, time since event: 6ms, device name: Wireless Numeric KeyPad Keyboard, descriptor: ac1ac0a0834a73ca12bdb5aa92681193d22281b7, device id: 26, is external: true, meta state: 2097152, scan code: 71
11:56:43.318  Down KEYCODE_DEL, key code: 67, time since event: 2ms, device name: Wireless Numeric KeyPad Keyboard, descriptor: ac1ac0a0834a73ca12bdb5aa92681193d22281b7, device id: 26, is external: true, meta state: 2097152, scan code: 14
11:56:43.321  Performed action OpenAppAction(packageName=com.samsung.android.app.appsedge), input event type: DOWN_UP, key meta state: 2097152
11:56:43.322  Down KEYCODE_DEL - consumed: true, key code: 67, time since event: 2ms, device name: Wireless Numeric KeyPad Keyboard, descriptor: ac1ac0a0834a73ca12bdb5aa92681193d22281b7, device id: 26, is external: true, meta state: 2097152, scan code: 14
11:56:43.527  Up KEYCODE_DEL, key code: 67, time since event: 3ms, device name: Wireless Numeric KeyPad Keyboard, descriptor: ac1ac0a0834a73ca12bdb5aa92681193d22281b7, device id: 26, is external: true, meta state: 2097152, scan code: 14
11:56:43.527  Up KEYCODE_DEL - consumed: true, key code: 67, time since event: 3ms, device name: Wireless Numeric KeyPad Keyboard, descriptor: ac1ac0a0834a73ca12bdb5aa92681193d22281b7, device id: 26, is external: true, meta state: 2097152, scan code: 14
11:56:44.555  Down KEYCODE_NUMPAD_DOT, key code: 158, time since event: 2ms, device name: Wireless Numeric KeyPad Keyboard, descriptor: ac1ac0a0834a73ca12bdb5aa92681193d22281b7, device id: 26, is external: true, meta state: 2097152, scan code: 83
11:56:44.556  Down KEYCODE_NUMPAD_DOT - consumed: false, key code: 158, time since event: 2ms, device name: Wireless Numeric KeyPad Keyboard, descriptor: ac1ac0a0834a73ca12bdb5aa92681193d22281b7, device id: 26, is external: true, meta state: 2097152, scan code: 83
11:56:44.763  Up KEYCODE_NUMPAD_DOT, key code: 158, time since event: 2ms, device name: Wireless Numeric KeyPad Keyboard, descriptor: ac1ac0a0834a73ca12bdb5aa92681193d22281b7, device id: 26, is external: true, meta state: 2097152, scan code: 83
11:56:44.764  Up KEYCODE_NUMPAD_DOT - consumed: false, key code: 158, time since event: 2ms, device name: Wireless Numeric KeyPad Keyboard, descriptor: ac1ac0a0834a73ca12bdb5aa92681193d22281b7, device id: 26, is external: true, meta state: 2097152, scan code: 83
11:56:47.312  MainActivity: onResume. Version: 2.3.0-debug
11:56:47.319  Accessibility service: checking if it is crashed
11:56:47.319  Battery optimisation is disabled
11:56:47.506  Service received event from UI: Ping(key=check_is_crashed)
11:56:47.506  Received event from service: Pong(key=check_is_crashed)
11:57:53.758  Accessibility service: checking if it is crashed
11:58:15.471  Accessibility service: checking if it is crashed
11:58:28.748  Accessibility service: checking if it is crashed
11:58:47.842  Accessibility service: checking if it is crashed
11:58:54.105  Accessibility service: checking if it is crashed
11:59:38.376  Accessibility service: checking if it is crashed
11:59:40.803  Accessibility service: checking if it is crashed
12:00:02.365  Accessibility service: checking if it is crashed
12:00:08.410  Accessibility service: checking if it is crashed
12:01:38.662  Accessibility service: checking if it is crashed
12:01:41.698  Accessibility service: checking if it is crashed
________________________________

**Comment by sds100** [comment]
Hm, interesting. So the issue is that Key Mapper isn't detecting the trigger now? Make sure the accessibility service of the Google Play version of Key Mapper is turned off. Can you send me a bug report from within Key Mapper. Follow this guide https://docs.keymapper.club/report-issues/

**Comment by brianmichaelwendt** [comment]
The accessibility service of the Google Play version of KeyMapper was on as you suspected. Turning it off corrected the "consumed: false" problem. The downloads folder still doesn't open. I did not create a bug report because I don't know if the hidden application named "Downloads" actually shows the downloads folder or even has a UI. Do you happen to know of a hidden app that definitely has a UI that I can use for testing?

Thanks,

Brian
________________________________

**Comment by sds100** [comment]
So opening a non-hidden app works (like the settings app)?

**Comment by brianmichaelwendt** [comment]
Yes, non-hidden apps work.

  By the way, are there any simple examples of using the new "intent" activity type in the documentation? To take a picture or open WiFi settings or something along those lines?

Brian
________________________________

**Comment by sds100** [comment]
Yeah, good idea. I will add a short tutorial to that section. But if you want to take a picture then you can use the "open camera" action and to open WiFi settings you can use the "app shortcut" action and then choose the settings app.

**Comment by sds100** [comment]
Can you send me a bug report by following this guide so I can try to figure out why your actions aren't working for hidden-apps https://docs.keymapper.club/report-issues/

**Comment by brianmichaelwendt** [comment]
The zip file is attached. When looking at the log file, there appears to be some old log entries, so scroll down to "15:25:10.106" to see the entries for the test I just performed. I pressed 7 on the numeric keypad and Instagram opened as expected. I pressed 3 on the numeric keypad (twice) and Downloads did not open.

Thanks,

Brian
________________________________

**Comment by brianmichaelwendt** [comment]
Thanks, I look forward to seeing it. I tried to figure it out myself but am not Android literate enough 🙂

  The "Open Camera" action does just that, opens the camera. I would like to open the camera and take a picture.

  "Settings" isn't listed under App Shortcuts but it is listed under Apps. Similar to the above, this opens the settings but does not go to the WiFi settings page.

Brian
________________________________

**Comment by sds100** [comment]
I haven't gotten the zip file because I think you attached to the email reply and didn't post the reply on github.com. I will create a separate issue for an action to take a picture. I will see if its possible to use the Intent action to do this right now.

**Comment by sds100** [comment]
Oh yeah, there isn't the app shortcut on Android TV. I will write the documentation. 🙂

**Comment by sds100** [comment]
@brianmichaelwendt This is a bug. The conversation will move to #794

**Comment by sds100** [comment]
@brianmichaelwendt it looks like apps cant open the Downloads app. It was wrong for Key Mapper to display all those apps as apps that you can choose as an action. It will only list apps that can be launched now #794
