### ISSUE TITLE
Overlapping triggers

### ISSUE THREAD

**Issue by AlexD97** [sds100/KeyMapper#653]
**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name
- [x] write tests. put issue number in comment
- [x] update documentation
- [ ] squash and merge
- [ ] delete branch

**Describe the bug**
If I define two “overlapping” shortcuts (e.g. Camera+Shift+Q -> A and Camera+Q -> B) and then enter the longer one (so in the example Camera+Shift+Q) I get both actions (in the example: AB)

**To Reproduce**
See example above.

**Expected behavior**
I would expect that only action A is executed.

[keymap.txt](https://github.com/sds100/KeyMapper/files/6373035/neo_layout_with_issue.txt)

**Smartphone (please complete the following information):**
 - Device: Galaxy Tab S7+
 - Android version: Android 11

**Comment by sds100** [comment]
Hello!

I think I fixed this issue but I haven't released it yet. Can you test this apk https://github.com/sds100/KeyMapper/suites/2514844077/artifacts/54425079

**Comment by AlexD97** [comment]
Hi, 
I tried the apk, but the issue unfortunately still exists.

**Comment by sds100** [comment]
[keymapper-2.3.0-alpha-debug_2.zip](https://github.com/sds100/KeyMapper/files/6447876/keymapper-2.3.0-alpha-debug_2.zip)
 @AlexD97 try this apk 😀

**Comment by AlexD97** [comment]
Thanks for your effort! 😃 Unfortunately things got even worse: the input is now extremely laggy and the default maps are not overridden properly (e.g. I mapped j to n; if I now type j I get jn, not just n).

**Comment by sds100** [comment]
You made 354 key maps! Wow

**Comment by sds100** [comment]
How come you made so many key maps? Are you trying to workaround the Android 11 bug which sets your keyboard layout to American English if an accessibility service is turned on? Key Mapper has an solution for that now 😄

**Comment by sds100** [comment]
Oh, okay. Interesting. This is the most "extreme" use case I have seen for Key Mapper. Will probably have to optimise it even more so it's not laggy 😂

**Comment by AlexD97** [comment]
Yeah, thank you! Version 2.2 is not laggy, so it only has to do something with this alpha version.

**Comment by sds100** [comment]
[keymapper-2.3.0-alpha-debug_3.zip](https://github.com/sds100/KeyMapper/files/6468669/keymapper-2.3.0-alpha-debug_3.zip)
this should hopefully fix the issue

**Comment by AlexD97** [comment]
So, the performance is now great, even better than in version 2.2!👍👍 
But the bug has become even weirder: If I press Camera+Shift+Q I get x…ξX instead of ξ. Also, if I press for example shift+j (where j is mapped to n) I get get nN (this happens for all characters) but if I press for example shift+`Comma` I get – and not ,– (so here it works).
I hope this is clear.

**Comment by sds100** [comment]
oh right, i see that you have also created key maps for when the buttons are pressed with modifier keys like Shift. You don't need to create key maps for when a key is presssed with a modifier. Key Mapper will handle this for you. For example if you just create a key map for J -> N then pressing Shift + J will input a capital N and without Shift it will be lower case

**Comment by sds100** [comment]
That just solves the issue for those keys. Still need to fix the Meta + ones...

**Comment by AlexD97** [comment]
Yes, indeed, that fixes the false behavior for Shift+<some key>...

**Comment by sds100** [comment]
[keymapper-2.3.0-alpha-debug.zip](https://github.com/sds100/KeyMapper/files/6473936/keymapper-2.3.0-alpha-debug.zip)
try this apk

**Comment by AlexD97** [comment]
The bug is gone! Thank you very much!😃

There is only one minor bug which appeared to me: Sometimes, the record trigger button doesn't work. Instead there is just "4...". I have to restart the app in order to work again. (But this has probably nothing to do with this bug here.)

**Comment by sds100** [comment]
Nice! I'll close this then. Can you reliably reproduce that issue?

**Comment by AlexD97** [comment]
No, I can't reliably reproduce it. It seems rather random when it happens...

**Comment by sds100** [comment]
Thank you! 😀
